// Categories that mark permit/approval items (used in AuditSession to split view)
export const PERMIT_CATEGORIES = new Set(['היתרים ואישורים', 'נהלים מוקדמים', 'תיעוד נדרש']);

export const PERMIT_ITEMS = {
  work: [
    { category: 'היתרים ואישורים', item_text: 'היתר עבודה חתום ע"י ממונה בטיחות — לפני תחילת כל יום עבודה', doc: '/docs/daily-work-permit.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור ממונה בטיחות לתחילת עבודה — תאריך, שעה וחתימה',         doc: '/docs/safety-start-approval.html' },
    { category: 'היתרים ואישורים', item_text: 'היתר עבודה חמה (ריתוך / חיתוך) — חתום, אם קיים בעבודה זו',   doc: '/docs/hot-work-permit.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הדרכת בטיחות ייעודית לעובדים לפני תחילת עבודה — תיעוד חתום', doc: '/docs/procedures-work.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הצגת גבולות האתר, מוצאי חירום וסיכונים לכל הצוות',           doc: '/docs/procedures-work.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ציוד מגן אישי לכל עובד לפני כניסה לשטח',               doc: '/docs/procedures-work.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הגדרת נוהל חירום, תפקידים ומיקום ערכת עזרה ראשונה',          doc: '/docs/procedures-work.html' },
    { category: 'תיעוד נדרש',      item_text: 'ציוד מגן אישי הונפק ואושר לכל עובד — רשימה חתומה',           doc: '/docs/procedures-work.html' },
    { category: 'תיעוד נדרש',      item_text: 'רשימת נוכחות עובדים עם אישורי הדרכת בטיחות',                 doc: '/docs/procedures-work.html' },
    { category: 'תיעוד נדרש',      item_text: 'טופס בדיקת ציוד יומי לפני שימוש — חתום על ידי אחראי',        doc: '/docs/procedures-work.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן בטיחות אתר — רישום תקינות, חריגות ואירועים',            doc: '/docs/procedures-work.html' },
  ],

  construction: [
    { category: 'היתרים ואישורים', item_text: 'היתר בנייה בתוקף מהרשות המקומית — מוצג באתר',                              doc: '/docs/procedures-construction.html' },
    { category: 'היתרים ואישורים', item_text: 'מינוי ממונה בטיחות לאתר הבנייה — בכתב, כולל פרטי קשר',                     doc: '/docs/procedures-construction.html' },
    { category: 'היתרים ואישורים', item_text: 'היתר עבודות חמות (ריתוך / חיתוך) — חתום לכל יום עבודה',                    doc: '/docs/hot-work-permit.html' },
    { category: 'היתרים ואישורים', item_text: 'תעודת כשירות עגורן / מנוף — בתוקף ומוצגת באתר',                           doc: '/docs/procedures-construction.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הודעה לביטוח לאומי על פתיחת אתר הבנייה — אישור קבלה',                      doc: '/docs/procedures-construction.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הכרזת תוכנית הבטיחות לכל הקבלנים והעובדים באתר',                           doc: '/docs/procedures-construction.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תדריך בטיחות לקבלני משנה לפני כניסה ראשונה לאתר',                          doc: '/docs/procedures-construction.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת אטימות חפירות עמוקות מ-1.5 מ׳ לפני כניסת עובדים',                   doc: '/docs/procedures-construction.html' },
    { category: 'תיעוד נדרש',      item_text: 'תוכנית בטיחות אתר בנייה — מאושרת ע"י מהנדס בטיחות',                       doc: '/docs/procedures-construction.html' },
    { category: 'תיעוד נדרש',      item_text: 'הסכמי בטיחות חתומים עם כל קבלני המשנה',                                    doc: '/docs/procedures-construction.html' },
    { category: 'תיעוד נדרש',      item_text: 'טופס בדיקת ציוד מכני יומי (עגורן, מחפרון, ציוד כבד)',                      doc: '/docs/procedures-construction.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן פיקוח בטיחות שבועי — ממצאים ותיקונים',                               doc: '/docs/procedures-construction.html' },
  ],

  infrastructure: [
    { category: 'היתרים ואישורים', item_text: 'היתר חפירה / עבודות תשתית מהרשות המקומית — בתוקף',                          doc: '/docs/procedures-infrastructure.html' },
    { category: 'היתרים ואישורים', item_text: 'היתר חסימת תנועה / עבודה בכביש — מרשות התחבורה הלאומית',                   doc: '/docs/procedures-infrastructure.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור תיאום תשתיות ממפ"י (מרכז מיפוי ישראל) — לפני חפירה',                  doc: '/docs/procedures-infrastructure.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור כתוב מחברות תשתית (חשמל, גז, מים, תקשורת) לביצוע חפירה',              doc: '/docs/procedures-infrastructure.html' },
    { category: 'נהלים מוקדמים',   item_text: 'סימון קווי תשתית קיימים בשטח ע"י גורם מוסמך — לפני חפירה',                 doc: '/docs/procedures-infrastructure.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הצבת תמרורי אזהרה ומסלול עוקף לפני תחילת עבודה בכביש',                    doc: '/docs/procedures-infrastructure.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תיאום עם משטרת ישראל לחסימה / הסדרת תנועה',                               doc: '/docs/procedures-infrastructure.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הודעה לביטוח לאומי על פתיחת אתר — אישור קבלה',                             doc: '/docs/procedures-infrastructure.html' },
    { category: 'תיעוד נדרש',      item_text: 'תוכנית הסדרי תנועה — מאושרת ע"י מהנדס תנועה',                             doc: '/docs/procedures-infrastructure.html' },
    { category: 'תיעוד נדרש',      item_text: 'פרוטוקול תיאום תשתיות — חתום על ידי כל ספקי התשתית',                      doc: '/docs/procedures-infrastructure.html' },
    { category: 'תיעוד נדרש',      item_text: 'טופס בדיקת בטיחות לפני כל כניסה לחפירה',                                  doc: '/docs/procedures-infrastructure.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן עבודה יומי — נוכחות, עבודות שבוצעו, חריגות',                         doc: '/docs/procedures-infrastructure.html' },
  ],

  industrial: [
    { category: 'היתרים ואישורים', item_text: 'רישיון עסק / היתר הפעלה מהרשות המקומית — בתוקף',                  doc: '/docs/procedures-industrial.html' },
    { category: 'היתרים ואישורים', item_text: 'היתר לאחסון חומרים מסוכנים — מאגף הסביבה, אם רלוונטי',            doc: '/docs/procedures-industrial.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור כיבוי אש לאחסון / שימוש בחומרים דליקים',                     doc: '/docs/procedures-industrial.html' },
    { category: 'היתרים ואישורים', item_text: 'מינוי ממונה בטיחות מוסמך — כתב מינוי ואישור רשות העבודה',          doc: '/docs/procedures-industrial.html' },
    { category: 'נהלים מוקדמים',   item_text: 'סקר סיכונים מקצועי שנתי — דוח חתום ע"י מהנדס בטיחות',             doc: '/docs/procedures-industrial.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הדרכת LOTO (ניתוק ונעילת אנרגיה) לכל מפעיל מכונות',               doc: '/docs/procedures-industrial.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הדרכת חומרים מסוכנים ו-SDS לכל עובד רלוונטי',                     doc: '/docs/procedures-industrial.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תרגיל פינוי שנתי בוצע ותועד — כולל תיקון ממצאים',                 doc: '/docs/procedures-industrial.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח ממונה בטיחות שנתי — חתום ומוגש לרשות המוסמכת',               doc: '/docs/procedures-industrial.html' },
    { category: 'תיעוד נדרש',      item_text: 'פנקס בדיקות מכונות וציוד — עם תאריכי בדיקה הבאים',                doc: '/docs/procedures-industrial.html' },
    { category: 'תיעוד נדרש',      item_text: 'רשימת מלאי חומרים מסוכנים — מעודכנת ונגישה',                      doc: '/docs/procedures-industrial.html' },
    { category: 'תיעוד נדרש',      item_text: 'תעודות הכשרה של עובדים — ארכיון עדכני',                            doc: '/docs/procedures-industrial.html' },
  ],

  traffic: [
    { category: 'היתרים ואישורים', item_text: 'היתר עבודה בכביש — מרשות התחבורה הלאומית, בתוקף',                         doc: '/docs/procedures-traffic.html' },
    { category: 'היתרים ואישורים', item_text: 'תכנית הסדרי תנועה — מאושרת ע"י מהנדס תנועה מוסמך',                       doc: '/docs/procedures-traffic.html' },
    { category: 'היתרים ואישורים', item_text: 'תיאום ואישור כתוב ממשטרת ישראל לחסימת / הסדרת כביש',                     doc: '/docs/procedures-traffic.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור ממחלקת תברואה / עירייה לחסימת מדרכה, אם רלוונטי',                  doc: '/docs/procedures-traffic.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הצבת תמרורים, גדרות ואלמנטים מחזירי אור לפני תחילת עבודה',               doc: '/docs/procedures-traffic.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת אפודי זוהר — לכל עובד הנמצא בסביבת תנועה',                        doc: '/docs/procedures-traffic.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הגדרת מסלול גישה לרכבי חירום לאורך כל האתר',                             doc: '/docs/procedures-traffic.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תדריך יומי לצוות על שינויי הסדרי תנועה ותפקידים',                        doc: '/docs/procedures-traffic.html' },
    { category: 'תיעוד נדרש',      item_text: 'פרוטוקול הצבת הסדרי תנועה — חתום ע"י מנהל עבודה',                       doc: '/docs/procedures-traffic.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן בדיקת ציוד ותמרורים בתחילת כל יום עבודה',                           doc: '/docs/procedures-traffic.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח אירועים ותאונות — הגשה לרשות התחבורה בתוך 24 שעות',                  doc: '/docs/procedures-traffic.html' },
  ],

  fire: [
    { category: 'היתרים ואישורים', item_text: 'היתר עבודות חמות (ריתוך / חיתוך / שריפה) — חתום לכל יום עבודה', doc: '/docs/hot-work-permit.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור שירותי כיבוי אש למתקני כיבוי ואזעקה — תעודה בתוקף',       doc: '/docs/procedures-fire.html' },
    { category: 'היתרים ואישורים', item_text: 'בדיקת מערכות כיבוי אש שנתית ע"י גורם מוסמך — תעודה בתוקף',      doc: '/docs/procedures-fire.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור שימוש במרחב ממינהל הבטיחות — לאחסון חומרים דליקים',         doc: '/docs/procedures-fire.html' },
    { category: 'נהלים מוקדמים',   item_text: 'פינוי חומרים דליקים מרדיוס 10 מ׳ מאזור עבודה חמה',              doc: '/docs/procedures-fire.html' },
    { category: 'נהלים מוקדמים',   item_text: 'מינוי שומר אש במהלך עבודה חמה ו-30 דקות לאחר סיומה',           doc: '/docs/procedures-fire.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת מטפי כיבוי אש בתחילת כל יום — תקינות ומיקום',            doc: '/docs/procedures-fire.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תדריך נוהל פינוי חירום ונקודות כינוס לכל הצוות',                doc: '/docs/procedures-fire.html' },
    { category: 'תיעוד נדרש',      item_text: 'פנקס היתרי עבודות חמות — ארכיון של כל ההיתרים הנפתחים',          doc: '/docs/procedures-fire.html' },
    { category: 'תיעוד נדרש',      item_text: 'תעודת בדיקה שנתית של מערכות כיבוי, גילוי ואזעקה',               doc: '/docs/procedures-fire.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח ביצוע תרגיל פינוי חירום — ממצאים ותיקונים',                 doc: '/docs/procedures-fire.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן בדיקות מטפי אש — תאריך בדיקה ותאריך הבאה',                 doc: '/docs/procedures-fire.html' },
  ],

  electrical: [
    { category: 'היתרים ואישורים', item_text: 'היתר עבודת חשמל — חתום ע"י חשמלאי מוסמך (רישיון בתוקף)',        doc: '/docs/procedures-electrical.html' },
    { category: 'היתרים ואישורים', item_text: 'תעודת בדיקת מיתקן חשמלי ע"י בודק מוסמך — בתוקף',              doc: '/docs/procedures-electrical.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור חברת חשמל לחיבור / שינוי מיתקן — אם רלוונטי',             doc: '/docs/procedures-electrical.html' },
    { category: 'נהלים מוקדמים',   item_text: 'טופס LOTO מולא ואושר — ניתוק ונעילת מקורות אנרגיה לפני עבודה', doc: '/docs/procedures-electrical.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ניתוק ואימות העדר מתח לפני נגיעה בחיווט',               doc: '/docs/procedures-electrical.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תיחום אזור עבודת חשמל — סימון ומניעת גישת אנשים לא מורשים',   doc: '/docs/procedures-electrical.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת כלי עבודה מבודדים לפני שימוש בסביבה חשמלית',             doc: '/docs/procedures-electrical.html' },
    { category: 'תיעוד נדרש',      item_text: 'תוכנית חשמל מעודכנת — נגישה בשטח ומשקפת את המצב הקיים',       doc: '/docs/procedures-electrical.html' },
    { category: 'תיעוד נדרש',      item_text: 'פרוטוקול LOTO — חתום לפני ואחרי כל עבודת תחזוקה',             doc: '/docs/procedures-electrical.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח בדיקת מיתקן חשמלי — תאריך ותוצאות',                        doc: '/docs/procedures-electrical.html' },
    { category: 'תיעוד נדרש',      item_text: 'ארכיון רישיונות חשמלאים — עדכני ונגיש לממונה',                  doc: '/docs/procedures-electrical.html' },
  ],

  scaffolding: [
    { category: 'היתרים ואישורים', item_text: 'תעודת בטיחות פיגום — חתומה ע"י מהנדס / בודק מוסמך',                    doc: '/docs/procedures-scaffolding.html' },
    { category: 'היתרים ואישורים', item_text: 'היתר עבודה בגובה — חתום ע"י ממונה בטיחות לכל עבודה',                   doc: '/docs/procedures-scaffolding.html' },
    { category: 'היתרים ואישורים', item_text: 'אישורי הדרכת עבודה בגובה — תעודות כל העובדים בתוקף',                   doc: '/docs/procedures-scaffolding.html' },
    { category: 'היתרים ואישורים', item_text: 'תעודת כשירות מנוף / גונדולה — אם נעשה שימוש',                         doc: '/docs/procedures-scaffolding.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת מצב פיגום יומית לפני כניסת עובדים — ע"י אחראי מוסמך',           doc: '/docs/procedures-scaffolding.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת רתמות ופלים לפני כל שימוש — תקינות וחיבור לנקודת עיגון',        doc: '/docs/procedures-scaffolding.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת תנאי מזג אוויר — הפסקת עבודה ברוח מעל 10 מ"ש',                 doc: '/docs/procedures-scaffolding.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הגבלת עומס על רצפת הפיגום — לא לחרוג מעומס תכנוני',                  doc: '/docs/procedures-scaffolding.html' },
    { category: 'תיעוד נדרש',      item_text: 'טופס מסירת פיגום — חתום ע"י מקים ומקבל לפני שימוש ראשון',             doc: '/docs/procedures-scaffolding.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן בדיקות פיגום יומי — חתום ע"י אחראי בטיחות',                     doc: '/docs/procedures-scaffolding.html' },
    { category: 'תיעוד נדרש',      item_text: 'ארכיון תעודות הדרכת גובה לכל עובד מורשה',                             doc: '/docs/procedures-scaffolding.html' },
    { category: 'תיעוד נדרש',      item_text: 'פרוטוקול פירוק פיגום — חתום בסיום, כולל ניקוי שטח',                   doc: '/docs/procedures-scaffolding.html' },
  ],

  confined: [
    { category: 'היתרים ואישורים', item_text: 'היתר כניסה למרחב מוגבל — חתום ע"י ממונה לכל אירוע כניסה',        doc: '/docs/procedures-confined.html' },
    { category: 'היתרים ואישורים', item_text: 'מינוי שומר כניסה מוסמך — בכתב, נוכח ואינו עוזב העמדה',          doc: '/docs/procedures-confined.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור תוכנית חילוץ חירום — מאושרת ומובנת לכל הצוות',             doc: '/docs/procedures-confined.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת אטמוספרה: חמצן (19.5%–23.5%), גזים דליקים, CO, H2S',     doc: '/docs/procedures-confined.html' },
    { category: 'נהלים מוקדמים',   item_text: 'ניטור מתמשך של איכות האוויר במהלך כל שהייה במרחב',              doc: '/docs/procedures-confined.html' },
    { category: 'נהלים מוקדמים',   item_text: 'ניתוק ונעילה (LOTO) של כל מקורות אנרגיה וצינורות',             doc: '/docs/procedures-confined.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ציוד חילוץ (חגורה, חבל, מרים) — תקין ומוכן בפתח',       doc: '/docs/procedures-confined.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ציוד נשימה (SCBA) — לחץ מספיק, תקין ומוכן לשימוש',      doc: '/docs/procedures-confined.html' },
    { category: 'תיעוד נדרש',      item_text: 'פרוטוקול בדיקת אטמוספרה — חתום לפני כל כניסה',                  doc: '/docs/procedures-confined.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן כניסות ויציאות — שם, שעה, ציוד, חתימת שומר',              doc: '/docs/procedures-confined.html' },
    { category: 'תיעוד נדרש',      item_text: 'אישור ביצוע תרגיל חילוץ — לפחות אחת לשנה',                     doc: '/docs/procedures-confined.html' },
  ],

  chemicals: [
    { category: 'היתרים ואישורים', item_text: 'רישיון לאחסון / שימוש בחומרים מסוכנים — מהמשרד להגנת הסביבה', doc: '/docs/procedures-chemicals.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור אחסון חומרים דליקים מאגף כיבוי אש',                      doc: '/docs/procedures-chemicals.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור פינוי פסולת מסוכנת ע"י קבלן מורשה',                      doc: '/docs/procedures-chemicals.html' },
    { category: 'נהלים מוקדמים',   item_text: 'גיליונות בטיחות (SDS) עדכניים לכל החומרים — נגישים לעובדים',  doc: '/docs/procedures-chemicals.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הדרכת עובדים על חומרים מסוכנים ונוהל SDS — תיעוד חתום',      doc: '/docs/procedures-chemicals.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ציוד מגן אישי מתאים לחומר לפני שימוש',                   doc: '/docs/procedures-chemicals.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ברז שטיפת עיניים ומקלחת חירום — תקינים ונגישים',        doc: '/docs/procedures-chemicals.html' },
    { category: 'נהלים מוקדמים',   item_text: 'נוהל שפיכה מוכר לכל הצוות — ציוד קליטת שפך בשטח',            doc: '/docs/procedures-chemicals.html' },
    { category: 'תיעוד נדרש',      item_text: 'רשימת מלאי חומרים מסוכנים — מעודכנת, חתומה, כולל כמויות',    doc: '/docs/procedures-chemicals.html' },
    { category: 'תיעוד נדרש',      item_text: 'ארכיון גיליונות SDS — מסודר, נגיש ועדכני לגרסה אחרונה',       doc: '/docs/procedures-chemicals.html' },
    { category: 'תיעוד נדרש',      item_text: 'תעודות הכשרה לעובדים בחומרים מסוכנים — עדכניות',              doc: '/docs/procedures-chemicals.html' },
    { category: 'תיעוד נדרש',      item_text: 'יומן פינוי פסולת מסוכנת — תאריכים, כמויות, מסמכי קבלן',      doc: '/docs/procedures-chemicals.html' },
  ],

  ergonomics: [
    { category: 'היתרים ואישורים', item_text: 'מינוי ממונה על בריאות ובטיחות תעסוקתית — כתב מינוי בתוקף',           doc: '/docs/procedures-ergonomics.html' },
    { category: 'היתרים ואישורים', item_text: 'אישור רופא תעסוקתי לביצוע בדיקות רפואיות תקופתיות',                  doc: '/docs/procedures-ergonomics.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הדרכת טכניקת הרמה נכונה לכל עובד — תיעוד וחתימה',                   doc: '/docs/procedures-ergonomics.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הערכת סיכוני ארגונומיה בכל עמדת עבודה — ע"י גורם מוסמך',             doc: '/docs/procedures-ergonomics.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הסדרת לוח זמנים להפסקות קצרות בעבודה פיזית מאומצת',                 doc: '/docs/procedures-ergonomics.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תכנית רוטציה לעמדות עם סיכון ארגונומי גבוה',                         doc: '/docs/procedures-ergonomics.html' },
    { category: 'נהלים מוקדמים',   item_text: 'הנחיית שימוש בעזרים מכניים (עגלות, מנופים) לכל הרמה כבדה',           doc: '/docs/procedures-ergonomics.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח הערכת סיכוני ארגונומיה — חתום ע"י מהנדס בטיחות',                 doc: '/docs/procedures-ergonomics.html' },
    { category: 'תיעוד נדרש',      item_text: 'תעודות הדרכה ארגונומית של עובדים — ארכיון עדכני',                    doc: '/docs/procedures-ergonomics.html' },
    { category: 'תיעוד נדרש',      item_text: 'תוצאות בדיקות רפואיות תקופתיות — בתוקף ומסודרות',                   doc: '/docs/procedures-ergonomics.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח בדיקת עמדות עבודה — המלצות ותיקונים שבוצעו',                    doc: '/docs/procedures-ergonomics.html' },
  ],

  emergency: [
    { category: 'היתרים ואישורים', item_text: 'תכנית חירום אתר — מאושרת ועדכנית, חתומה ע"י ממונה בטיחות',         doc: '/docs/procedures-emergency.html' },
    { category: 'היתרים ואישורים', item_text: 'מינוי ממונה פינוי ראשי וממלאי מקום — כתב מינוי בכתב',               doc: '/docs/procedures-emergency.html' },
    { category: 'היתרים ואישורים', item_text: 'תיאום תכנית חירום עם כבאות, מד"א ומשטרה — אישור בכתב',              doc: '/docs/procedures-emergency.html' },
    { category: 'נהלים מוקדמים',   item_text: 'תדריך חירום שנתי לכל הצוות — נוהל פינוי ונקודות כינוס',            doc: '/docs/procedures-emergency.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת ערכות עזרה ראשונה — תכולה, תפוגות וזמינות',                  doc: '/docs/procedures-emergency.html' },
    { category: 'נהלים מוקדמים',   item_text: 'בדיקת מערכת כריזה / אזעקה — תקינות ושמיעות',                       doc: '/docs/procedures-emergency.html' },
    { category: 'נהלים מוקדמים',   item_text: 'עדכון רשימת אנשי קשר לחירום — תאריך עדכון וחתימה',                  doc: '/docs/procedures-emergency.html' },
    { category: 'נהלים מוקדמים',   item_text: 'ביצוע תרגיל פינוי שנתי — מתועד ומחולץ ממצאים',                     doc: '/docs/procedures-emergency.html' },
    { category: 'תיעוד נדרש',      item_text: 'תכנית חירום כתובה — מוצגת בכל קומה / מתחם',                        doc: '/docs/procedures-emergency.html' },
    { category: 'תיעוד נדרש',      item_text: 'רשימת אנשי קשר לחירום — מעודכנת ומוצגת בנקודות מרכזיות',           doc: '/docs/procedures-emergency.html' },
    { category: 'תיעוד נדרש',      item_text: 'דוח ביצוע תרגיל פינוי — ממצאים, זמני תגובה, תיקונים',              doc: '/docs/procedures-emergency.html' },
    { category: 'תיעוד נדרש',      item_text: 'תעודות הסמכת מוסמכי עזרה ראשונה — עדכניות (חידוש כל 3 שנים)',      doc: '/docs/procedures-emergency.html' },
  ],
};

export const AUDIT_TYPES = {
  work:           { label: 'בטיחות בעבודה כללית',     icon: '🏗️',  sector: 'general' },
  construction:   { label: 'בטיחות אתר בנייה',         icon: '🧱',  sector: 'construction' },
  infrastructure: { label: 'עבודות תשתית',              icon: '⛏️',  sector: 'construction' },
  industrial:     { label: 'בטיחות מפעל / תעשייה',     icon: '🏭',  sector: 'industrial' },
  traffic:        { label: 'בטיחות בתנועה',             icon: '🚦',  sector: 'general' },
  fire:           { label: 'בטיחות אש וחירום',          icon: '🔥',  sector: 'general' },
  electrical:     { label: 'בטיחות חשמל',               icon: '⚡',  sector: 'general' },
  scaffolding:    { label: 'פיגומים ועבודה בגובה',      icon: '🪜',  sector: 'construction' },
  confined:       { label: 'מרחבים מוגבלים',            icon: '🚪',  sector: 'general' },
  chemicals:      { label: 'חומרים מסוכנים',            icon: '☣️',  sector: 'industrial' },
  ergonomics:     { label: 'ארגונומיה ועומס גופני',     icon: '🦺',  sector: 'general' },
  emergency:      { label: 'מוכנות לחירום ופינוי',      icon: '🚨',  sector: 'general' },
};

export const CHECKLIST_ITEMS = {
  work: [
    { category: 'ציוד מגן אישי',    item_text: 'ציוד מגן אישי מתאים בשימוש (קסדה, נעליים, אפוד)' },
    { category: 'ציוד מגן אישי',    item_text: 'ציוד הגנה לעיניים ופנים זמין כנדרש' },
    { category: 'עבודה בגובה',      item_text: 'גידור ואבטחת פיגומים תקינים' },
    { category: 'עבודה בגובה',      item_text: 'רתמות בטיחות מחוברות לנקודת עיגון' },
    { category: 'כלי עבודה',        item_text: 'כלי עבודה ומכשירים תקינים ובדוקים' },
    { category: 'כלי עבודה',        item_text: 'אחסון בטוח של כלים וחומרים' },
    { category: 'סדר וניקיון',      item_text: 'מסלולי מעבר מסומנים ופנויים' },
    { category: 'סדר וניקיון',      item_text: 'שמירה על סדר וניקיון באזור העבודה' },
    { category: 'חומרים מסוכנים',   item_text: 'אחסון בטוח של חומרים מסוכנים עם סימון מתאים' },
    { category: 'אש וחירום',        item_text: 'מטפי כיבוי אש תקינים ונגישים' },
    { category: 'אש וחירום',        item_text: 'תאורת חירום ומוצאי חירום מסומנים' },
  ],

  construction: [
    { category: 'גידור ופרוטקציה',  item_text: 'גידור פריפריאלי תקין ורציף סביב האתר' },
    { category: 'גידור ופרוטקציה',  item_text: 'רשתות בטיחות מתוחות מתחת לרמות עבודה בגובה' },
    { category: 'פיגומים',          item_text: 'פיגומים הוקמו על ידי גורם מוסמך ויש תעודת בטיחות' },
    { category: 'פיגומים',          item_text: 'מעקות ביניים ורצפת פיגום תקינים (לא נפערים, לא שבורים)' },
    { category: 'עבודה בגובה',      item_text: 'כל עובד מעל 2 מטר חגור רתמה המחוברת לנקודת עיגון' },
    { category: 'עבודה בגובה',      item_text: 'פתחים ובורות מגודרים ומסומנים' },
    { category: 'ציוד מכני',        item_text: 'עגורן / מנוף — תעודת כושר בתוקף ומוצגת' },
    { category: 'ציוד מכני',        item_text: 'אופרטור ציוד כבד — רישיון בתוקף ובדיקה שנתית' },
    { category: 'חפירות',           item_text: 'חפירות מעל 1.5 מ׳ — עמודי תמיכה / מדרגות מעוגלות' },
    { category: 'חפירות',           item_text: 'גידור וסימון מסביב לחפירות הפתוחות' },
    { category: 'חשמל',             item_text: 'לוח חשמל זמני — מוגן, מכוסה ומאורק' },
    { category: 'חשמל',             item_text: 'כבלים חשמליים לא מונחים על הרצפה ללא הגנה' },
    { category: 'ציוד מגן אישי',    item_text: 'קסדה, נעלי בטיחות ואפוד זוהר — כל עובד' },
    { category: 'סדר ניקיון',       item_text: 'פסולת בנייה מפונה באופן שוטף' },
  ],

  infrastructure: [
    { category: 'חפירות וחשיפה',    item_text: 'גידור ותמרור סביב חפירות בכביש / מדרכה' },
    { category: 'חפירות וחשיפה',    item_text: 'תאורת לילה ואלמנטים מחזירי אור בכל שעות החשכה' },
    { category: 'חפירות וחשיפה',    item_text: 'תמיכת דפנות חפירה עמוקה מ-1.5 מטר' },
    { category: 'צינורות ורשתות',   item_text: 'תיאום עם חברות תשתית לאיתור קווים קיימים' },
    { category: 'צינורות ורשתות',   item_text: 'סימון קווי תשתית בשטח לפני כל חפירה' },
    { category: 'בטיחות תנועה',     item_text: 'תמרורי אזהרה ומסלול עוקף בתוקף לאורך האתר' },
    { category: 'בטיחות תנועה',     item_text: 'עובדים נוכחים בכביש — אפוד זוהר ומוצב שוטר/מכוון' },
    { category: 'ציוד מכני',        item_text: 'כלי עבודה כבדים (מחפרון, בובקט) — בדיקה יומית לפני שימוש' },
    { category: 'ציוד מגן אישי',    item_text: 'ציוד מגן אישי מלא לכל עובד באתר' },
    { category: 'חשמל',             item_text: 'גנרטורים — הארקה נכונה ומרחק מבטיחות מחומרים דליקים' },
    { category: 'תקשורת',           item_text: 'נוהל תקשורת מוגדר עם פיקוד בשעת חירום' },
  ],

  industrial: [
    { category: 'מכונות ציוד',      item_text: 'כל מכונה מסוכנת מוגנת במגן קבוע (Guard) תקין' },
    { category: 'מכונות ציוד',      item_text: 'נוהל Lockout/Tagout (LOTO) — תחזוקה בעת כיבוי' },
    { category: 'מכונות ציוד',      item_text: 'כפתורי עצירת חירום (E-Stop) נגישים ובדוקים' },
    { category: 'חומרים מסוכנים',   item_text: 'גיליונות בטיחות (SDS) זמינים לכל חומר מסוכן' },
    { category: 'חומרים מסוכנים',   item_text: 'אחסון חומרים דליקים בארון מוגן אש, כמות מוגבלת' },
    { category: 'חומרים מסוכנים',   item_text: 'ציוד לסילוק שפכים ותכולת ערכת חירום מכימיקלים' },
    { category: 'גהות תעסוקתית',    item_text: 'אוורור מספיק באזורי ריכוז אדים / אבק / ריחות' },
    { category: 'גהות תעסוקתית',    item_text: 'בדיקת רעש תקופתית — שימוש בפקקי אוזניים במידת הצורך' },
    { category: 'ציוד מגן אישי',    item_text: 'ציוד מגן אישי מתאים לסיכונים ספציפיים בכל עמדה' },
    { category: 'אש וחירום',        item_text: 'ממטרות ספרינקלרים / גלאי עשן — תקינות ולא חסומים' },
    { category: 'אש וחירום',        item_text: 'נתיבי פינוי חירום מסומנים ולא חסומים' },
    { category: 'הכשרה',            item_text: 'עובדים עברו הדרכת בטיחות ספציפית לעמדתם' },
    { category: 'הכשרה',            item_text: 'תרגיל פינוי אש בוצע ב-12 החודשים האחרונים' },
  ],

  fire: [
    { category: 'ציוד כיבוי',        item_text: 'מטפי כיבוי אש תקינים, בתוקף ונגישים' },
    { category: 'ציוד כיבוי',        item_text: 'ארונות שריפה (כבאי) תקינים עם צינור וראש מים' },
    { category: 'ציוד כיבוי',        item_text: 'ספרינקלרים — אין חסימה, בדיקה שנתית בתוקף' },
    { category: 'גלאים',             item_text: 'גלאי עשן / חום פעילים ולא מחוסמים' },
    { category: 'גלאים',             item_text: 'מערכת אזעקה פעילה ונבדקת אחת לרבעון' },
    { category: 'מוצאי חירום',       item_text: 'שלטי יציאת חירום מוארים ומסומנים' },
    { category: 'מוצאי חירום',       item_text: 'דלתות חירום נפתחות מבפנים ללא מפתח' },
    { category: 'מוצאי חירום',       item_text: 'מסלולי פינוי פנויים מחסימות' },
    { category: 'דלתות אש',          item_text: 'דלתות אש נסגרות אוטומטית ולא מעוכבות' },
    { category: 'תחזוקה',            item_text: 'תרגיל פינוי בוצע ב-12 החודשים האחרונים' },
    { category: 'תחזוקה',            item_text: 'אין אחסון חומרים דליקים ליד מקורות חום' },
    { category: 'תחזוקה',            item_text: 'חדרי חשמל / ממ"ד — ללא פסולת דליקה' },
  ],

  electrical: [
    { category: 'לוחות חשמל',        item_text: 'לוחות חשמל סגורים, מסומנים ונגישים לטכנאי' },
    { category: 'לוחות חשמל',        item_text: 'מפסקי פחת (RCD/GFCI) מותקנים ובדוקים' },
    { category: 'לוחות חשמל',        item_text: 'אין חיבורים זמניים בלוח (חוטים חשופים)' },
    { category: 'כבלים וחיבורים',    item_text: 'כבלים ללא נזק, שחיקה או חשיפת חוטים' },
    { category: 'כבלים וחיבורים',    item_text: 'כבלים מונחים בצנרת או מוגנים מפני דריסה' },
    { category: 'כבלים וחיבורים',    item_text: 'שקעים תקינים, לא שבורים, ללא עומס יתר' },
    { category: 'הארקה',             item_text: 'הארקה תקינה לכל ציוד חשמלי' },
    { category: 'הארקה',             item_text: 'מוט הארקה ראשי קיים ומחובר' },
    { category: 'עבודות חשמל',       item_text: 'עבודות חשמל מבוצעות רק ע"י חשמלאי מוסמך' },
    { category: 'עבודות חשמל',       item_text: 'נוהל Lockout מיושם בתחזוקת מתקנים' },
    { category: 'סביבה רטובה',       item_text: 'ציוד חשמלי בסביבה רטובה — דרגת הגנה IP מתאימה' },
    { category: 'תיעוד',             item_text: 'תוכנית חשמל מעודכנת ונגישה' },
  ],

  scaffolding: [
    { category: 'הקמה ומבנה',        item_text: 'פיגום הוקם ע"י בעל מקצוע מוסמך' },
    { category: 'הקמה ומבנה',        item_text: 'תעודת בטיחות פיגום ממהנדס חתומה' },
    { category: 'הקמה ומבנה',        item_text: 'בסיסי הפיגום יציבים על קרקע מוצקה ומשוּוים' },
    { category: 'הקמה ומבנה',        item_text: 'חיבורים ומהדקים מסוג מאושר ובמצב תקין' },
    { category: 'רצפות ומעקות',      item_text: 'לוחות רצפה שלמים, ללא פערים מעל 3 ס"מ' },
    { category: 'רצפות ומעקות',      item_text: 'מעקה עליון (100 ס"מ), אמצעי ותחתון (10 ס"מ)' },
    { category: 'כניסה ועלייה',      item_text: 'סולם עלייה מאובטח ובטיחותי' },
    { category: 'כניסה ועלייה',      item_text: 'כניסה אחת בלבד מסומנת לפיגום' },
    { category: 'עובדים',            item_text: 'כל עובד בפיגום חגור רתמה ומחובר לנקודת עיגון' },
    { category: 'עובדים',            item_text: 'אין עומס יתר של חומרים על הפיגום' },
    { category: 'בדיקות',            item_text: 'בדיקת פיגום לאחר כל מזג אוויר קשה' },
    { category: 'בדיקות',            item_text: 'רישום יומי של בדיקת מצב הפיגום' },
  ],

  confined: [
    { category: 'הרשאות',            item_text: 'היתר כניסה למרחב מוגבל חתום לפני כניסה' },
    { category: 'הרשאות',            item_text: 'נוהל כניסה למרחב מוגבל מאושר ומוכר לצוות' },
    { category: 'בדיקות אוויר',      item_text: 'בדיקת ריכוז חמצן (19.5%–23.5%) לפני כניסה' },
    { category: 'בדיקות אוויר',      item_text: 'בדיקת גזים דליקים ורעילים (CO, H2S וכד׳)' },
    { category: 'בדיקות אוויר',      item_text: 'ניטור מתמשך של איכות האוויר במהלך העבודה' },
    { category: 'ציוד חירום',        item_text: 'ציוד נשימה (SCBA / SABA) זמין ובדוק' },
    { category: 'ציוד חירום',        item_text: 'ציוד חילוץ (חגורה, חבל) ממוקם בכניסה' },
    { category: 'תקשורת',            item_text: 'תקשורת רציפה בין עובד בפנים לשומר בחוץ' },
    { category: 'שומר כניסה',        item_text: 'שומר כניסה נוכח ולא עוזב את עמדתו' },
    { category: 'אנרגיה',            item_text: 'כל מקורות אנרגיה מנוטרלים ונעולים (LOTO)' },
    { category: 'כניסה ויציאה',      item_text: 'פתח הכניסה רחב מספיק לחילוץ עם ציוד' },
  ],

  chemicals: [
    { category: 'זיהוי וסימון',       item_text: 'כל חומר מסוכן מסומן לפי תקן GHS / אוניקוד' },
    { category: 'זיהוי וסימון',       item_text: 'גיליונות בטיחות (SDS) נגישים לכל עובד' },
    { category: 'אחסון',              item_text: 'חומרים דליקים באוגרים מוגני אש ייעודיים' },
    { category: 'אחסון',              item_text: 'הפרדה בין חומרים שאינם תואמים (חומצה/בסיס וכד׳)' },
    { category: 'אחסון',              item_text: 'כמות מינימלית בשטח העבודה, שאר במחסן' },
    { category: 'טיפול',              item_text: 'ציוד מגן אישי מתאים (כפפות, משקפי מגן, סינר)' },
    { category: 'טיפול',              item_text: 'אוורור מספיק בעת שימוש בחומרים נדיפים' },
    { category: 'טיפול',              item_text: 'ברז שטיפת עיניים / מקלחת חירום נגישים' },
    { category: 'פסולת',              item_text: 'פסולת מסוכנת מסומנת ומאוחסנת לפני פינוי' },
    { category: 'פסולת',              item_text: 'פינוי פסולת מסוכנת ע"י גוף מורשה' },
    { category: 'הכשרה',              item_text: 'עובדים עברו הדרכה ספציפית לחומרים בשימוש' },
    { category: 'חירום',              item_text: 'נוהל זיהום / שפיכה ידוע לכל הצוות' },
  ],

  ergonomics: [
    { category: 'הרמה וסחיבה',        item_text: 'עובדים הודרכו לטכניקת הרמה נכונה' },
    { category: 'הרמה וסחיבה',        item_text: 'משקלות מעל 25 ק"ג — עזרה מכנית / שניים' },
    { category: 'הרמה וסחיבה',        item_text: 'עגלות הובלה זמינות ומתאימות לצרכים' },
    { category: 'תנוחת עבודה',        item_text: 'גובה משטחי עבודה מותאם לעובדים' },
    { category: 'תנוחת עבודה',        item_text: 'אין חובת עמידה/ישיבה ממושכת ללא הפסקות' },
    { category: 'תנוחת עבודה',        item_text: 'עמדות עם עבודה חוזרת — בדיקת תנוחה וכלים' },
    { category: 'כלי עבודה',          item_text: 'כלים מתאימים לגודל יד ולא דורשים לחץ יתר' },
    { category: 'כלי עבודה',          item_text: 'ידיות עם ריפוד / הגנה מרטט' },
    { category: 'סביבה',              item_text: 'תאורה מספקת למניעת מאמץ עיניים' },
    { category: 'סביבה',              item_text: 'טמפרטורת עבודה סבירה (לא חום / קור קיצוני)' },
    { category: 'הפסקות',             item_text: 'הפסקות קצרות מוגדרות בעבודה פיזית מאומצת' },
  ],

  emergency: [
    { category: 'תכנית חירום',        item_text: 'תכנית חירום כתובה ומאושרת קיימת' },
    { category: 'תכנית חירום',        item_text: 'נקודות כינוס לחירום מסומנות ומוכרות לכולם' },
    { category: 'תכנית חירום',        item_text: 'רשימת אנשי קשר לחירום מעודכנת ומוצגת' },
    { category: 'פינוי',              item_text: 'מסלולי פינוי מסומנים בבניין / אתר' },
    { category: 'פינוי',              item_text: 'תרגיל פינוי בוצע ב-12 החודשים האחרונים' },
    { category: 'פינוי',              item_text: 'ממונה פינוי מוגדר לכל קומה / מתחם' },
    { category: 'עזרה ראשונה',        item_text: 'ערכות עזרה ראשונה מאוישות ומסומנות' },
    { category: 'עזרה ראשונה',        item_text: 'לפחות 2 מוסמכי עזרה ראשונה בכל משמרת' },
    { category: 'ממ"ד / מרחב מוגן',  item_text: 'ממ"ד / מרחב מוגן נגיש ולא חסום' },
    { category: 'ממ"ד / מרחב מוגן',  item_text: 'ממ"ד נקי מאחסון ודלת אוטמת תקינה' },
    { category: 'תקשורת',             item_text: 'מערכת כריזה / התרעה פעילה ונבדקת' },
    { category: 'תקשורת',             item_text: 'נוהל דיווח אירוע חירום ידוע לכל המפקחים' },
  ],

  traffic: [
    { category: 'שילוט',            item_text: 'תמרורים ושילוט מתאים בכניסה לאתר' },
    { category: 'שילוט',            item_text: 'שילוט מהירות ואזהרה בכביש האתר' },
    { category: 'הפרדת תנועה',      item_text: 'הפרדת מסלולי הולכי רגל מרכבים' },
    { category: 'הפרדת תנועה',      item_text: 'מחסומים פיזיים בין אזורי עבודה לתנועה' },
    { category: 'כניסה ויציאה',     item_text: 'מחסומים ושערים תקינים בכניסה' },
    { category: 'כניסה ויציאה',     item_text: 'נהג מכוון בכניסה לאתר בשעות עמוסות' },
    { category: 'חניה',             item_text: 'אזורי חניה מסומנים ומאורגנים' },
    { category: 'חניה',             item_text: 'חניית כלי רכב כבדים נפרדת ומאובטחת' },
    { category: 'תאורה',            item_text: 'תאורת לילה מספקת בנתיבי תנועה' },
    { category: 'נהגים',            item_text: 'נהגים מורשים בלבד לכלי רכב כבדים' },
  ],

};
